/* automatically generated by ocaml-bindgen 0.0.1 */

#include "doggo.h"
#include <caml/alloc.h>
#include <caml/callback.h>
#include <caml/fail.h>
#include <caml/memory.h>
#include <caml/mlvalues.h>
#include <caml/unixsupport.h>
void caml_print_age(value caml_age) {
  CAMLparam1(caml_age);
  int* age = Nativeint_val(Field(caml_age, 1));
  print_age(age);
  CAMLreturn0;
}

void caml_print_name(value caml_name) {
  CAMLparam1(caml_name);
  char* name = Nativeint_val(Field(caml_name, 1));
  print_name(name);
  CAMLreturn0;
}


#include <stdlib.h>
value bindgen_alloc(value caml_size) {
    CAMLparam1(caml_size);

    // Convert OCaml integer to C size
    size_t size = Int_val(caml_size);
    printf("Allocated size %ld \n", size);

    void* ptr = malloc(sizeof(size));
    if (ptr == NULL) {
        // TODO: handle allocation failure
        CAMLreturn(Val_unit);
    }
    
    // Wrap the pointer as an OCaml value
    CAMLreturn(caml_copy_nativeint(ptr));
}

void bindgen_free(value caml_addr) {
    free(Nativeint_val(caml_addr));
}

value bindgen_alloc_string(value caml_string) {
  CAMLparam1(caml_string);
    char* str = String_val(caml_string);
    CAMLreturn(caml_copy_nativeint((intnat)str));
}
